"use client";

import { motion } from "framer-motion";
import { Info, AlertTriangle, ShieldCheck } from "lucide-react";
import { useState } from "react";

export function InteractivePreview() {
  const [activeTooltip, setActiveTooltip] = useState<string | null>(null);

  return (
    <section id="demo" className="py-24 bg-brand-bg relative overflow-hidden border-t border-black/5">
      <div className="absolute inset-0 bg-gradient-to-b from-transparent to-brand-bg z-0" />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-3xl md:text-5xl font-bold tracking-tight mb-6"
          >
            See exactly what changed.
          </motion.h2>
          <p className="text-lg text-brand-text-secondary">
            Hover over the highlighted changes below to see how raylinr translates legal risk into business impact.
          </p>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="glass rounded-2xl border border-black/10 shadow-2xl overflow-hidden max-w-5xl mx-auto"
        >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-black/5 bg-black/5">
            <div className="flex items-center gap-4">
              <span className="font-semibold text-brand-text-primary">MSA_AcmeCorp_v2_Redlined.pdf</span>
              <span className="px-2 py-1 rounded text-xs font-medium bg-brand-risk/20 text-brand-risk flex items-center gap-1">
                <AlertTriangle className="w-3 h-3" /> 2 High Risks
              </span>
            </div>
            <div className="flex gap-2">
              <button className="px-3 py-1.5 text-xs font-medium text-brand-text-secondary hover:text-brand-text-primary transition-colors">Compare</button>
              <button className="px-3 py-1.5 text-xs font-medium bg-black/5 rounded hover:bg-black/10 transition-colors">Export</button>
            </div>
          </div>

          {/* Document Content */}
          <div className="p-8 md:p-12 space-y-8 bg-brand-surface text-brand-text-primary font-serif leading-loose relative min-h-[400px]">
            
            {/* Clause 1 */}
            <div className="relative">
              <p className="text-sm md:text-base">
                <strong className="font-bold mr-2 text-brand-text-primary">4.2 IP Ownership.</strong> 
                Customer retains all rights to Customer Data. Provider retains all rights to the Services and any 
                <span 
                  className="relative mx-1 cursor-pointer"
                  onMouseEnter={() => setActiveTooltip("ip")}
                  onMouseLeave={() => setActiveTooltip(null)}
                >
                  <span className="bg-brand-warning/20 text-brand-warning border-b-2 border-brand-warning/50 hover:bg-brand-warning/30 transition-colors px-1 rounded font-medium">
                    derivative works, improvements, or modifications made by either party
                  </span>
                  
                  {/* Tooltip */}
                  {activeTooltip === "ip" && (
                    <motion.div 
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-72 glass bg-brand-surface p-4 rounded-xl shadow-xl z-50 border-l-4 border-l-brand-warning cursor-default"
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <AlertTriangle className="w-4 h-4 text-brand-warning" />
                        <span className="text-xs font-bold uppercase text-brand-warning">Medium Risk</span>
                      </div>
                      <p className="text-sm font-sans leading-tight mb-2">Vendor is claiming ownership of improvements made by YOUR team.</p>
                      <p className="text-xs text-brand-text-secondary font-sans">Playbook violation: We never surrender IP generated by our employees. Counter-offer to strike "made by either party".</p>
                    </motion.div>
                  )}
                </span>
                during the Term.
              </p>
            </div>

            {/* Clause 2 */}
            <div className="relative">
              <p className="text-sm md:text-base">
                <strong className="font-bold mr-2 text-brand-text-primary">9.1 Indemnification.</strong> 
                Provider shall indemnify Customer against third-party claims alleging that the Services infringe any intellectual property right, 
                <span 
                  className="relative mx-1 cursor-pointer"
                  onMouseEnter={() => setActiveTooltip("indemnity")}
                  onMouseLeave={() => setActiveTooltip(null)}
                >
                  <span className="bg-brand-risk/20 text-brand-risk border-b-2 border-brand-risk/50 hover:bg-brand-risk/30 transition-colors px-1 rounded font-medium">
                    provided that Customer's sole and exclusive remedy shall be limited to a pro-rata refund of fees paid
                  </span>

                  {/* Tooltip */}
                  {activeTooltip === "indemnity" && (
                    <motion.div 
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-72 glass bg-brand-surface p-4 rounded-xl shadow-xl z-50 border-l-4 border-l-brand-risk cursor-default"
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <Info className="w-4 h-4 text-brand-risk" />
                        <span className="text-xs font-bold uppercase text-brand-risk">High Risk</span>
                      </div>
                      <p className="text-sm font-sans leading-tight mb-2">Vendor gutted their IP indemnity.</p>
                      <p className="text-xs text-brand-text-secondary font-sans">If you are sued because their software steals IP, they will only refund your subscription fee. You would be liable for the rest of the lawsuit. Escalate to Legal immediately.</p>
                    </motion.div>
                  )}
                </span>
                .
              </p>
            </div>

            {/* Clause 3 */}
            <div className="relative opacity-60">
              <p className="text-sm md:text-base">
                <strong className="font-bold mr-2 text-brand-text-primary">10.3 Governing Law.</strong> 
                This Agreement shall be governed by the laws of the State of Delaware, without regard to its conflict of laws principles.
              </p>
            </div>

          </div>
        </motion.div>
      </div>
    </section>
  );
}
